### ISSUE TITLE
Error: persistentvolumeclaims "grafana" not found

### ISSUE THREAD

**Issue by ahmedelnahel** [mlrun/ce#34]
Hi, I'm trying to install on docker desktop with  -f override-full.yaml  set, I'm getting the grafana error "Error: persistentvolumeclaims "grafana" not found" 

Any idea how to fix this issue?

**Comment by quaark** [comment]
Hey @ahmedelnahel,
The chart assumes your kubernetes cluster has a default storage class (In cloud clusters or in minikube this is already configured by default).
In the Prerequisites section in the install README.md this is mentioned with an example of using rancher's `local-path`. But you can refer to https://kubernetes.io/docs/concepts/storage/storage-classes/#the-storageclass-resource for more options.
